services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./hospital-appointment-api
    container_name: backend
    command: sh -c "npm run seed && npm run dev"
    ports:
      - "3000:3000"
    env_file:
      - ./hospital-appointment-api/.env
    depends_on:
      - mongo
    volumes:
      - ./hospital-appointment-api:/app:cached
      - /app/node_modules

  frontend:
    build:
      context: ./hospital-appointment-app
    container_name: frontend
    stdin_open: true
    tty: true
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - BACKEND_URL=http://${LOCAL_IP}:3000
      - LOCAL_IP=${LOCAL_IP}
    depends_on:
      - backend
    volumes:
      - ./hospital-appointment-app:/app:cached
      - /app/node_modules

volumes:
  mongo_data:
